### ISSUE TITLE
Extension naming

### ISSUE THREAD

**Issue by thegecko** [eclipse-cdt-cloud/vscode-peripheral-inspector#11]
Type: Feature Request

In its current state, this repo cannot be published to the marketplace because it has the same ID as the original `svd-viewer`.

It is possible to move the publisher of this extension to resolve the issue, however existing installs of `cortex-debug.svd-viewer` will fail. see: https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-7591479

Should we try to keep the name or deprecate it in favour of a new name, e.g.:

- svd-inspector
- peripheral-inspector
- svd-explorer
- others?

cc @asimgunes, @jreineckearm

**Comment by asimgunes** [comment]
Hi @thegecko,

My personal opinion is the project has a potential to expand its capabilities to other system definition formats. The fundemental goal of the project could be considered as "define a UI extension for embedded system developers that they can explore the peripherals information".  

If we consider the goal in that way, SVD will be one of the formats supported by the extension and, semantically, we can think about renaming the extension to something like "peripheral-explorer" or "peripheral-inspector" or something which may have more general meaning.

**Comment by jreineckearm** [comment]
Hi @thegecko , I agree with @asimgunes . With a more generic name, this extension could become the home for other technologies and views to support inspection of peripherals in embedded systems. Making a start with SVD.

In terms of exact naming, we should probably look for something that is consistent with other extensions in `eclipse-cdt-cloud`. Considering that we have a `Memory Inspector` extension already, I'd suggest to go with "Peripheral Inspector".

**Comment by thegecko** [comment]
Great, I'll rename this to `peripheral-inspector`

**Comment by thegecko** [comment]
See #12

**Comment by thegecko** [comment]
#12 Has been merged, now awaiting repo name change at https://github.com/eclipse-cdt-cloud/.eclipsefdn/pull/9

**Comment by thegecko** [comment]
All renaming complete and initial version published
