### ISSUE TITLE
Peripheral Inspector extension is not available in remote ssh state

### ISSUE THREAD

**Issue by lyflyaway** [eclipse-cdt-cloud/vscode-peripheral-inspector#30]
Type: Feature Request

Hello, as the following picture, in the Visual Studio Code remote ssh state, Peripheral Inspector extension is not available. Could you add this feature? Thank you!

![Peripheral Inspector](https://github.com/user-attachments/assets/9343e956-9c37-445f-a507-9c67881eed9d)

**Comment by lyflyaway** [comment]
Hello thegecko,

After I add "workspace" in the package.json, the Peripheral Inspector extension state is change, as the following picture, is no longer gray, but it indicates Reload Window.

Even though I click Reload Window, it still doesn't work and indicates Reload Window again. Could you help me take a look at it? Thank you!

![Peripheral Inspector state](https://github.com/user-attachments/assets/8066fff5-1a07-4c1d-a66f-4faa5f0e010f)
![Peripheral Inspector is not loaded](https://github.com/user-attachments/assets/b6fd7952-15ba-4b82-b231-4fb93167d762)

**Comment by thegecko** [comment]
The error suggests there is a hard dependency between extensions. I would recommend you don't have a concrete coupling like this as it causes a lot of issues.

The approach I would recommend:
- If you want to install extensions in a bundle - have your main one act as an [extensionPack](https://code.visualstudio.com/api/references/extension-manifest#extension-packs) (in your case this looks like `renesas debug` is the main one)
- If you rely on functionality in another extension, check it is installed first (`vscode.extensions.all`) and fail gracefully. If its there you can activate it to get the Api or call known commands from it

**Comment by markgoodchild** [comment]
@thegecko , Hi Rob,

Thank you for working on this issue.

Regarding this change - will you publish this extension soon?
It seems that users cannot see this change currently?

Many thanks,
Mark.

**Comment by jreineckearm** [comment]
We have been working with our friends from EclipseSource on a series of changes that refresh the GUI and will in future allow a more convenient way of editing values (see not yet merged #46).

I believe we are in a state to have restored functionality from before. So, we might be good with publishing a new release before we add more functionality. Followed by another release soon to get in #46.

Ideally, we would spend a little more time on testing. We in particular haven't tested the API approach of filling the viewer due to the lack of a reproducer. @thegecko , do you remember who might be able to help with testing that scenario on `main`?

**Comment by thegecko** [comment]
You mean the `non-svd` support adsed by @asimgunes in https://github.com/eclipse-cdt-cloud/vscode-peripheral-inspector/pull/8 ?

**Comment by markgoodchild** [comment]
Firstly thank you for the work on this area. It is appreciated.

We are very keen to see a quick resolution on this bit:
>>  Visual Studio Code remote ssh state, Peripheral Inspector extension is not available. 

The other bits are not so urgent from our point of view.

**Comment by jreineckearm** [comment]
> You mean the non-svd support added by @asimgunes in https://github.com/eclipse-cdt-cloud/vscode-peripheral-inspector/pull/8 ?

Yes, that's the one.

> The other bits are not so urgent from our point of view.

OK, understood. We'll hold back then the next changes and focus on making a release.

**Comment by jreineckearm** [comment]
Thanks, @asimgunes , for sharing this! That gives a good idea of how testing this could be done. Actually not too complicated.

**Comment by jreineckearm** [comment]
This fix is now released in v1.6.0.
