### ISSUE TITLE
Cannot install Peripheral Inspector on remote-SSH

### ISSUE THREAD

**Issue by QuocTrung76** [eclipse-cdt-cloud/vscode-peripheral-inspector#35]
Type: Bug Report

**Describe the bug**
Cannot install Peripheral Inspector on Remote-SSH

**To Reproduce**
The Renesas Debug extension integrates the Peripheral Inspector. However, when installing Renesas Debug on Remote-SSH, it gets stuck during the installation of the Peripheral Inspector extension.

**Expected behavior**

The Peripheral Inspector extension was successfully installed on Remote-SSH.

**Comment by thegecko** [comment]
This was fixed in #31
